[template_input_parameters.project_name]
template_value = "#{project_name}#"
condition = "\\b[a-zA-Z]+\\b"
description = "Project Name"

[template_input_parameters.deployment_region]
template_value = "#{deployment_region}#"
condition = "^[a-z]{2}-[a-z]{4,10}-\\d$"
description = "Aws Region"

[template_input_parameters.backend_bucket]
template_value = "#{backend_bucket}#"
condition = "^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$"
description = "Backend Bucket for tfstate"

[template_input_parameters.backend_region]
template_value = "#{backend_region}#"
condition = "^[a-z]{2}-[a-z]{4,10}-\\d$"
description = "Backend Aws Region"

[template_input_parameters.owner]
template_value = "#{owner}#"
condition = "\\b[a-zA-Z]+\\b"
description = "Team or role owner for this deployment"

[template_input_parameters.client]
template_value = "#{client}#"
condition = "\\b[a-zA-Z]+\\b"
description = "Client or Area for this deployment"

[template_input_parameters.backend_dynamodb]
template_value = "#{backend_dynamodb}#"
condition = "^[a-zA-Z0-9_.-]{3,255}$"
description = "Dynamodb for lock state"

[template_input_parameters.environment]
template_value = "#{environment}#"
condition = "(dev|qa|stg|test|prod)"
description = "The environment or workspace name for initial setup. Environment allowed values (dev|qa|stg|test|prod)"

[template_input_parameters.cloud_provider]
template_value = "#{cloud_provider}#"
condition = "(aws|azure|oci|gcp)"
description = "The environment or workspace name for initial setup. Environment allowed values (aws|azure|oci|gcp)"


[template_input_parameters.deployment_profile]
template_value = "#{deployment_profile}#"
condition = "^[a-zA-Z0-9_.-]{3,255}$"
description = "Deployment profile aws cli"

[template_input_parameters.backend_profile]
template_value = "#{backend_profile}#"
condition = "^[a-zA-Z0-9_.-]{3,255}$"
description = "Backend profile for s3 remote state"


[project_properties]
project_name = "gitops-scale"
deployment_region = "us-east-2"
backend_bucket = "labvel-artifacts-terraform-tfsta"
backend_region = "us-east-2"
owner = "labvel"
client = "labvel"
backend_dynamodb = "db-terraform-loc"
environment = "dev"
cloud_provider = "aws"
deployment_profile = "labvel-dev"
backend_profile = "labvel-devsecops"
[iacpb]
project_id = "terragrunt_aws_gitops_blueprint"
